spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hh_automator
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

hh:
  api:
    url: https://api.hh.ru
    token: ${HH_TOKEN:test}
